name: .NET

on: workflow_dispatch
# on:
#   push:
#     branches: [ "main" ]
#     paths:
#       - "./src/webapi"
#   pull_request:
#     branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install Amazon.Lambda.Tools
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Restore dependencies
      working-directory: ./src/webapi/HelloLambda.v1
      run: dotnet restore
    - name: Build
      working-directory: ./src/webapi/HelloLambda.v1
      run: dotnet build --no-restore
    - name: Deploy
      working-directory: ./src/webapi/HelloLambda.v1
      run: dotnet lambda deploy-function HelloLambda
