name: v2 - .NET

on: workflow_dispatch
# on:
#   push:
#     branches: [ "main" ]
#     paths:
#       - "./src/functions"
#   pull_request:
#     branches: [ "main" ]

env:
  AWS_REGION: eu-north-1 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install Amazon.Lambda.Tools
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Restore dependencies
      working-directory: ./src/functions/HelloLambda.v2/src/HelloLambda.v2
      run: dotnet restore
    - name: Build
      working-directory: ./src/functions/HelloLambda.v2/src/HelloLambda.v2
      run: dotnet build --no-restore
    - name: Deploy
      working-directory: ./src/functions/HelloLambda.v2/src/HelloLambda.v2
      run: dotnet lambda deploy-function HelloLambda
