name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Provisioning environment     
        required: true
        default: test
      action:
        type: choice
        description: Terraform action
        required: true
        default: plan
        options: 
        - plan
        - apply

env:
  ENV_AWS_REGION: eu-north-1
  ENV_STATE_FILE_STORAGE_NAME: tf-state-file-00001

permissions:
  contents: read

jobs:
  terraform:
    name: 'Infra. provisioning w/ Terraform'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.9
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.ENV_AWS_REGION }}
    - name: Init
      working-directory: ./src
      run: ./provision.sh -a init -e ${{ github.event.inputs.environment }}
    - name: Action (${{ github.event.inputs.action }})
      working-directory: ./src
      run: ./provision.sh -a ${{ github.event.inputs.action }} -e ${{ github.event.inputs.environment }}

