name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        description: Who to greet
        type: choice
        required: false
        options: 
        - monalisa
        - cschleiden
      message:
        description: Some message
        required: true
      use-emoji:
        description: Include 🎉🤣 emojis
        required: false
        type: boolean
      environment:
        description: Environment info
        required: false
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", "🥳"]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"